
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.tfc]
			acacia = true
			ash = true
			aspen = true
			birch = true
			blackwood = true
			chestnut = true
			douglas_fir = true
			hickory = true
			kapok = true
			mangrove = true
			maple = true
			oak = true
			palm = true
			pine = true
			rosewood = true
			sequoia = true
			spruce = true
			sycamore = true
			white_cedar = true
			willow = true

		[types.wood_type.allthemodium]
			demonic = true
			soul = true

		[types.wood_type.integrateddynamics]
			menril = true

		[types.wood_type.gtceu]
			rubber = true

	[types.leaves_type]

		[types.leaves_type.allthemodium]
			ancient = true
			demonic = true
			soul = true

		[types.leaves_type.integrateddynamics]
			menril = true

		[types.leaves_type.gtceu]
			rubber = true

	[types.stone_type]

		[types.stone_type.scguns]
			phosphorite = true

		[types.stone_type.allthemodium]
			ancient_stone = true

		[types.stone_type.iceandfire]
			dread_stone = true

		[types.stone_type.create]
			cut_granite = true
			cut_diorite = true
			cut_andesite = true
			cut_calcite = true
			cut_dripstone = true
			cut_deepslate = true
			cut_tuff = true
			cut_asurine = true
			cut_crimsite = true
			cut_limestone = true
			cut_ochrum = true
			cut_scoria = true
			cut_scorchia = true
			cut_veridium = true

		[types.stone_type.gtceu]
			coke_oven = true
			red_granite = true
			marble = true
			light_concrete = true
			dark_concrete = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			trim = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.create]
			window_pane = true
			window = true

