name = "Homestead 1.0.1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "B75861FDF4253BAF6AB53FCD80492FC3884ADB6549B76B4BDA63A09CC8877C6B"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
