name = "Homestead 1.0.1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dc2b9e738be7ddc0b1300642717806f63eacdaa9828f031196aa8ff012a8915"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
